#! /bin/bash

PROC_NAME='xxl-job-admin'
ProcNumber=`ps -ef |grep -w $PROC_NAME|grep -v grep|wc -l`
if [ $ProcNumber -le 0 ];then
   echo "${PROC_NAME} is not run"
   nohup java -jar /opt/appsoftware/xxx-job/taskexecutor/xxl-job-admin-2.2.0-SNAPSHOT.jar  &
else
   echo "${PROC_NAME} is  running.."
fi
